auto:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: auto
    username: root
    password: 2117350690a
  redis:
    host: localhost
    port: 6379
    password: 2117350690a
    #数据库 --- 默认给了16个数据库，不同数据库的数据是完全隔离的
    database: 1
